In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [2]:
df = pd.read_csv("../dataset/processed/cleaned_dataset.csv")

In [3]:
df.head(5)

,Brand,Model,YOM,Engine (cc),Gear,Fuel Type,Millage(KM),Town,Date,Leasing,Condition,AIR CONDITION,POWER STEERING,POWER MIRROR,POWER WINDOW,Price
0,AUDI,A1,2016.0,990.0,Automatic,Petrol,99000.0,Gampaha,2025-02-05,No Leasing,USED,Available,Available,Available,Available,100.0
1,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Colombo,2025-01-14,No Leasing,USED,Available,Available,Available,Available,97.0
2,AUDI,A1,2018.0,1000.0,Automatic,Petrol,77000.0,Dehiwala-Mount-Lavinia,2025-01-23,No Leasing,USED,Available,Available,Available,Available,98.5
3,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Negombo,2024-12-21,No Leasing,USED,Available,Available,Available,Available,107.0
4,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Colombo,2024-12-21,No Leasing,USED,Available,Available,Available,Available,99.5

In [4]:
df.head(20)

,Brand,Model,YOM,Engine (cc),Gear,Fuel Type,Millage(KM),Town,Date,Leasing,Condition,AIR CONDITION,POWER STEERING,POWER MIRROR,POWER WINDOW,Price
0,AUDI,A1,2016.0,990.0,Automatic,Petrol,99000.0,Gampaha,2025-02-05,No Leasing,USED,Available,Available,Available,Available,100.000
1,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Colombo,2025-01-14,No Leasing,USED,Available,Available,Available,Available,97.000
2,AUDI,A1,2018.0,1000.0,Automatic,Petrol,77000.0,Dehiwala-Mount-Lavinia,2025-01-23,No Leasing,USED,Available,Available,Available,Available,98.500
3,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Negombo,2024-12-21,No Leasing,USED,Available,Available,Available,Available,107.000
4,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Colombo,2024-12-21,No Leasing,USED,Available,Available,Available,Available,99.500
5,AUDI,A1,2018.0,1500.0,Automatic,Petrol,77000.0,Colombo,2024-12-16,No Leasing,USED,Available,Available,Available,Available,91.375
6,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Matara,2024-12-11,No Leasing,USED,Available,Available,Available,Available,104.000
7,AUDI,A1 RS,2016.0,1000.0,Automatic,Petrol,99000.0,Colombo,2025-01-19,No Leasing,USED,Available,Available,Available,Available,105.000
8,AUDI,A3 SPORTBACK,2017.0,1000.0,Automatic,Petrol,88000.0,Battaramulla,2025-02-01,No Leasing,USED,Available,Available,Not_Available,Available,125.000
9,AUDI,A4,2001.0,1900.0,Manual,Diesel,264000.0,Piliyandala,2025-02-04,No Leasing,USED,Available,Available,Available,Available,38.800
10,AUDI,A4,2010.0,1800.0,Automatic,Petrol,165000.0,Kotte,2025-02-03,No Leasing,USED,Available,Available,Available,Available,118.000
11,AUDI,A4,2011.0,2000.0,Automatic,Petrol,154000.0,Colombo,2025-01-18,Ongoing Lease,USED,Available,Available,Available,Available,125.000
12,AUDI,A4,1999.0,1900.0,Manual,Diesel,286000.0,Anuradapura,2025-01-09,No Leasing,USED,Available,Available,Available,Available,31.500
13,AUDI,A4,2003.0,1800.0,Automatic,Petrol,242000.0,Moratuwa,2025-01-06,No Leasing,USED,Available,Available,Available,Available,53.600
14,AUDI,A4,2011.0,2000.0,Automatic,Diesel,154000.0,Colombo,2025-01-27,No Leasing,USED,Available,Available,Not_Available,Available,108.000
15,AUDI,A4,2011.0,2000.0,Automatic,Diesel,154000.0,Kegalle,2024-12-28,No Leasing,USED,Available,Available,Available,Available,116.500
16,AUDI,A4,2010.0,1800.0,Automatic,Petrol,165000.0,Gampaha,2024-12-26,No Leasing,USED,Available,Available,Available,Available,100.000
17,AUDI,A4 1.9 TDI,2001.0,1900.0,Manual,Diesel,264000.0,Kotte,2025-01-16,No Leasing,USED,Available,Available,Available,Available,5.000
18,AUDI,A4 B8,2011.0,1800.0,Automatic,Petrol,154000.0,Weligama,2025-01-25,No Leasing,USED,Available,Available,Available,Available,112.000
19,AUDI,A4 S LINE,2010.0,1800.0,Automatic,Petrol,165000.0,Galle,2025-01-10,No Leasing,USED,Available,Available,Available,Available,102.000

In [5]:
df["Car_Age"] = 2025 - df["YOM"]
df["Mileage_per_Year"] = df["Millage(KM)"] / df["Car_Age"].replace(0, 1)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9309 entries, 0 to 9308
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             9309 non-null   object
 1   Model             9309 non-null   object
 2   YOM               9309 non-null   float64
 3   Engine (cc)       9309 non-null   float64
 4   Gear              9309 non-null   object
 5   Fuel Type         9309 non-null   object
 6   Millage(KM)       9309 non-null   float64
 7   Town              9309 non-null   object
 8   Date              9309 non-null   object
 9   Leasing           9309 non-null   object
 10  Condition         9309 non-null   object
 11  AIR CONDITION     9309 non-null   object
 12  POWER STEERING    9309 non-null   object
 13  POWER MIRROR      9309 non-null   object
 14  POWER WINDOW      9309 non-null   object
 15  Price             9309 non-null   float64
 16  Car_Age           9309 non-null   float64
 17  Mileage_per_Year  9309 non-null   float64
dtypes: float64(6), object(12)
memory usage: 1.3+ MB

In [7]:
df["Engine_Category"] = pd.cut(
    df["Engine (cc)"],
    bins=[0, 1000, 2000, 4000, float("inf")],
    labels=["Small", "Medium", "Large", "Very Large"]
)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9309 entries, 0 to 9308
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             9309 non-null   object
 1   Model             9309 non-null   object
 2   YOM               9309 non-null   float64
 3   Engine (cc)       9309 non-null   float64
 4   Gear              9309 non-null   object
 5   Fuel Type         9309 non-null   object
 6   Millage(KM)       9309 non-null   float64
 7   Town              9309 non-null   object
 8   Date              9309 non-null   object
 9   Leasing           9309 non-null   object
 10  Condition         9309 non-null   object
 11  AIR CONDITION     9309 non-null   object
 12  POWER STEERING    9309 non-null   object
 13  POWER MIRROR      9309 non-null   object
 14  POWER WINDOW      9309 non-null   object
 15  Price             9309 non-null   float64
 16  Car_Age           9309 non-null   float64
 17  Mileage_per_Year  9309 non-null   float64
 18  Engine_Category   9309 non-null   category
dtypes: category(1), float64(6), object(12)
memory usage: 1.3+ MB

In [9]:
df["Date"] = pd.to_datetime(df["Date"])
df["Year_Listed"] = df["Date"].dt.year
df["Month_Listed"] = df["Date"].dt.month

In [10]:
binary_cols = ["POWER WINDOW", "POWER MIRROR", "POWER STEERING", "AIR CONDITION"]

mapping = {"Available": 1, "Not_Available": 0}

for col in binary_cols:
    df[col] = df[col].map(mapping)

In [11]:
df.head(20)

,Brand,Model,YOM,Engine (cc),Gear,Fuel Type,Millage(KM),Town,Date,Leasing,...,AIR CONDITION,POWER STEERING,POWER MIRROR,POWER WINDOW,Price,Car_Age,Mileage_per_Year,Engine_Category,Year_Listed,Month_Listed
0,AUDI,A1,2016.0,990.0,Automatic,Petrol,99000.0,Gampaha,2025-02-05,No Leasing,...,1,1,1,1,100.000,9.0,11000.0,Small,2025,2
1,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Colombo,2025-01-14,No Leasing,...,1,1,1,1,97.000,8.0,11000.0,Small,2025,1
2,AUDI,A1,2018.0,1000.0,Automatic,Petrol,77000.0,Dehiwala-Mount-Lavinia,2025-01-23,No Leasing,...,1,1,1,1,98.500,7.0,11000.0,Small,2025,1
3,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Negombo,2024-12-21,No Leasing,...,1,1,1,1,107.000,8.0,11000.0,Small,2024,12
4,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Colombo,2024-12-21,No Leasing,...,1,1,1,1,99.500,8.0,11000.0,Small,2024,12
5,AUDI,A1,2018.0,1500.0,Automatic,Petrol,77000.0,Colombo,2024-12-16,No Leasing,...,1,1,1,1,91.375,7.0,11000.0,Medium,2024,12
6,AUDI,A1,2017.0,1000.0,Automatic,Petrol,88000.0,Matara,2024-12-11,No Leasing,...,1,1,1,1,104.000,8.0,11000.0,Small,2024,12
7,AUDI,A1 RS,2016.0,1000.0,Automatic,Petrol,99000.0,Colombo,2025-01-19,No Leasing,...,1,1,1,1,105.000,9.0,11000.0,Small,2025,1
8,AUDI,A3 SPORTBACK,2017.0,1000.0,Automatic,Petrol,88000.0,Battaramulla,2025-02-01,No Leasing,...,1,1,0,1,125.000,8.0,11000.0,Small,2025,2
9,AUDI,A4,2001.0,1900.0,Manual,Diesel,264000.0,Piliyandala,2025-02-04,No Leasing,...,1,1,1,1,38.800,24.0,11000.0,Medium,2025,2
10,AUDI,A4,2010.0,1800.0,Automatic,Petrol,165000.0,Kotte,2025-02-03,No Leasing,...,1,1,1,1,118.000,15.0,11000.0,Medium,2025,2
11,AUDI,A4,2011.0,2000.0,Automatic,Petrol,154000.0,Colombo,2025-01-18,Ongoing Lease,...,1,1,1,1,125.000,14.0,11000.0,Medium,2025,1
12,AUDI,A4,1999.0,1900.0,Manual,Diesel,286000.0,Anuradapura,2025-01-09,No Leasing,...,1,1,1,1,31.500,26.0,11000.0,Medium,2025,1
13,AUDI,A4,2003.0,1800.0,Automatic,Petrol,242000.0,Moratuwa,2025-01-06,No Leasing,...,1,1,1,1,53.600,22.0,11000.0,Medium,2025,1
14,AUDI,A4,2011.0,2000.0,Automatic,Diesel,154000.0,Colombo,2025-01-27,No Leasing,...,1,1,0,1,108.000,14.0,11000.0,Medium,2025,1
15,AUDI,A4,2011.0,2000.0,Automatic,Diesel,154000.0,Kegalle,2024-12-28,No Leasing,...,1,1,1,1,116.500,14.0,11000.0,Medium,2024,12
16,AUDI,A4,2010.0,1800.0,Automatic,Petrol,165000.0,Gampaha,2024-12-26,No Leasing,...,1,1,1,1,100.000,15.0,11000.0,Medium,2024,12
17,AUDI,A4 1.9 TDI,2001.0,1900.0,Manual,Diesel,264000.0,Kotte,2025-01-16,No Leasing,...,1,1,1,1,5.000,24.0,11000.0,Medium,2025,1
18,AUDI,A4 B8,2011.0,1800.0,Automatic,Petrol,154000.0,Weligama,2025-01-25,No Leasing,...,1,1,1,1,112.000,14.0,11000.0,Medium,2025,1
19,AUDI,A4 S LINE,2010.0,1800.0,Automatic,Petrol,165000.0,Galle,2025-01-10,No Leasing,...,1,1,1,1,102.000,15.0,11000.0,Medium,2025,1

In [12]:
df["Leasing"] = df["Leasing"].apply(lambda x: 1 if "Leasing" in x else 0)

In [13]:
df["Brand_Freq"] = df["Brand"].map(df["Brand"].value_counts())
df["Model_Freq"] = df["Model"].map(df["Model"].value_counts())

In [14]:
df["Brand_AvgPrice"] = df.groupby("Brand")["Price"].transform("mean")
df["Model_AvgPrice"] = df.groupby("Model")["Price"].transform("mean")

In [15]:
brand_freq_map = df["Brand"].value_counts().to_dict()
model_freq_map = df["Model"].value_counts().to_dict()

brand_avg_map = df.groupby("Brand")["Price"].mean().to_dict()
model_avg_map = df.groupby("Model")["Price"].mean().to_dict()

In [16]:
luxury_brands = {"AUDI","BMW","MERCEDES","LEXUS","JAGUAR","LAND ROVER","PORSCHE","VOLVO"}
df["Luxury_Brand"] = df["Brand"].apply(lambda x: 1 if x.upper() in luxury_brands else 0)

In [17]:
X = df.drop(columns=["Price", "Date", "Model", "Town"])

y = df["Price"]

In [18]:
binary_cols = ["POWER WINDOW", "POWER MIRROR", "POWER STEERING", "AIR CONDITION", "Leasing", "Luxury_Brand"]
categorical = ["Brand", "Gear", "Fuel Type", "Condition", "Engine_Category"]
numeric = [col for col in X.columns if col not in categorical + binary_cols]

In [19]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical),
        ("bin", "passthrough", binary_cols)
    ]
)

In [20]:
X_transformed = preprocessor.fit_transform(X)

In [21]:
num_features = numeric
bin_features = binary_cols
cat_features = preprocessor.named_transformers_["cat"].get_feature_names_out(categorical)
feature_names = list(num_features) + list(bin_features) + list(cat_features)

In [22]:
X_transformed_df = pd.DataFrame(
    X_transformed.toarray() if hasattr(X_transformed, "toarray") else X_transformed,
    columns=feature_names
)

In [23]:
processed_df = X_transformed_df.copy()
processed_df["Price"] = y.values

In [24]:
processed_df.to_csv(
    "../dataset/processed/preprocessed_car_price_dataset.csv",
    index=False
)
print("Preprocessed dataset saved successfully!")

Preprocessed dataset saved successfully!